### ISSUE TITLE
OptiX version?

### ISSUE THREAD

**Issue by ghost** [galdar496/heatray#2]
Hello. Will heatray in OptiX version?

**Comment by galdar496** [comment]
No it is openrl only

**Comment by ghost** [comment]
I looked all samples with OpenRL, but theys too slow, as I can predict - slower than OptiX. OptiX uses GPU, while OpenRL support only specific hardware and CPU (AVX of first revision).

**Comment by galdar496** [comment]
Yeah openrl is not gpu-accelerated
