### ISSUE TITLE
OpenRL SDK

### ISSUE THREAD

**Issue by KorolevSoftware** [galdar496/heatray#3]
Hello, I find OpenRL sdk and documentation, can you give me link? There is no mention of this library on the official website imagination.

**Comment by galdar496** [comment]
Yeah I don't think Imagination ships this library anymore. You can find the SDK under Heatray's 3rdParty directory. As for the documentation I unfortunately no longer have it.

**Comment by KorolevSoftware** [comment]
The library has a very interesting interface like OpenGL. Thank you.
